### ISSUE TITLE
~3월 24일 과제

### ISSUE THREAD

**Issue by whitedot** [whitedot/sirpub-bo#1]
1. 아래 스크린샷과 **동일하게** 구성
1. 우상단 더보기 클릭 시 스샷 2번처럼 컨텐츠 영역 나타나도록
    1. 컨텐츠 영역은 빈 상태로 나타나도 됨

**스샷 1번**
![image](https://cloud.githubusercontent.com/assets/1720041/13869627/044a987a-ed1a-11e5-893a-6fde62107bed.png)

**스샷2번**
![image](https://cloud.githubusercontent.com/assets/1720041/13869630/13fcdbc0-ed1a-11e5-9b5a-15805c96c016.png)

**Comment by whitedot** [comment]
be98c8c57568ec7d147b81a5f1b9ebba1da9b785
1e22f3e2e77a9fa1ca33b9a8444d356b1826b629

**Comment by whitedot** [comment]
http://egloos.zum.com/njpaiks/v/2412118
http://www.fastcompany.com/3016894/should-your-tag-be-your-logo
http://stackoverflow.com/questions/665037/replacing-h1-text-with-a-logo-image-best-method-for-seo-and-accessibility
http://csswizardry.com/2010/10/your-logo-is-an-image-not-a-h1/

**Comment by leebokyung** [comment]
책에서 보거나 w3c에 들어가서 봐도 로고나 타이틀에 h1이 사용되었습니다.
개인적인 의견도 마찬가지로 h1은 로고 또는 타이틀에 단 한번만 사용되어야 된다고 생각합니다.

어제 책으로 예시를 들어 봤었잖아요?
제가 생각하는 책에 문서 구조는 이렇습니다.

'나미야 잡화점의 기적'이라는 책으로 예를 들겠습니다.

이 책의 제목은 '나미야 잡화점의 기적' 입니다.
책의 목차에는

제1장 답장은 우유 상자에 
제2장 한밤중에 하모니카를 
제3장 시빅 자동차에서 아침까지 
제4장 묵도는 비틀스로 
제5장 하늘 위에서 기도를 

이렇게 5가지로 나뉘어 있습니다. 5가지 모두 큰 연관성이 없는 '별개의 내용'입니다.
제 1장~ 은 h2가 되겠죠.
제 1장 '답장은 우유 상자에'의 내용에는 제목에 맞는 내용으로 구성되어 있습니다.
제 1장의 내용을 이끄는 제목은 어떻게 보면 h1이 맞다고 생각됩니다. 내용의 제목이니까요.
하지만 제 1장은 책의 제목인 '나미야 잡화점의 기적'의 책 속의 내용에서 나뉘어진 컨텐츠 입니다.
그래서 문서의 중요 내용이 '제1장 답장은 우유 상자에'일지라도 중제목으로 넘어가 h2가 된다고 생각합니다.

팀장님이 말씀하시는건 대략 

<h1>대제목: 페이지, 혹은 문서에서 **가장 중요한 제목**</h1>
<h2>중제목</h2>
<h3>소제목</h3>
<h4>소소제목</h4>
<h5>소소소제목</h5>
<h6>소소소소제목</h6>

이런거라고 생각하는데, 저도 무슨말인지 이해합니다.
하지만 정해진 답이 없는 것 같고, 정확히 명시되지 않은 사실이기도 해서 구분하기 힘든 것 같아요.

**Comment by whitedot** [comment]
문서 아웃라인 확인 https://gsnedders.html5.org/outliner/

**Comment by whitedot** [comment]
문서 아웃라인을 잡을 때 고려할 요소

1. 해당 페이지 자체에 집중
2. 검색엔진 최적화
3. 접근성 (스크린리더 사용성)
